services:
  db:
    image: postgres:16
    container_name: booktracker_db
    networks:
      - booknet
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: booktracker_adminer
    networks:
      - booknet
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    ports:
      - "8888:8080"

networks:
  booknet:
    driver: bridge
